### ISSUE TITLE
Use as formatter

### ISSUE THREAD

**Issue by OliverJAsh** [amatiasq/vsc-sort-imports#15]
VSCode has the concept of file formatters which can be ran using the `Format Document` command. This command can also be configured to run on save with `"editor.formatOnSave": true`.

Have you thought about adding `sort-imports` as a formatter? This would provide consistent with other formatters like Prettier.

**Comment by amatiasq** [comment]
I didn't know that, that would be an amazing addition to integrate with VS. Do you know where  to find documentation about this?

**Comment by OliverJAsh** [comment]
This might help: https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices

**Comment by amatiasq** [comment]
We were talking about this in [#7](https://github.com/amatiasq/vsc-sort-imports/issues/7#issuecomment-365750303). The problem is VSCode only allows one formatter at the time and we don't want to force users to choose between `sort-imports` and any other formatter out there because it's not what this extension is focused on.
