### ISSUE TITLE
Can I break up long imports into multiple lines?

### ISSUE THREAD

**Issue by natesilva** [amatiasq/vsc-sort-imports#21]
If I have:

```typescript
import { functionB, functionC, functionG, functionA, functionH, functionF, functionE, functionD, functionI } from 'somewhere';
```

Can I break that into separate lines when sorting, maybe based on line length?

```typescript
import { functionA, functionB, functionC, functionD } from 'somewhere';
import { functionE, functionF, functionG, functionH } from 'somewhere';
```

**Comment by fsmaia** [comment]
I think this syntax is a little unusual, and it's usually blocked by ESLint's [`import/no-duplicates`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-duplicates.md) rule.

Since splitting into one member per line is not a problem, may I suggest you to use tools like EditorConfig and Prettier to handle format? These ones, specially Prettier, can enforce a code style in terms of legibility, and eliminate the need to actively care about it.

**Comment by natesilva** [comment]
We’re using TSLint, and we don’t have the `no-duplicate-imports` rule enabled. We have a database module from which we might import a dozen or more things. Either we have very long lines, or, with Prettier, we get this yuckiness:

```typescript
import {
  functionA,
  functionB,
  functionC,
  functionD,
  functionE,
  functionF,
  functionG,
  functionH
} from 'somewhere';
```

I’ll check out the settings in EditorConfig and Prettier to see if it can be improved.

**Comment by amatiasq** [comment]
In my opinion having two imports for the same module is confusing, giving the idea that the imports are coming from different modules.

The multiline import is a standard solution for this situations.

Anyway I'll leave this open for discussion.

**Comment by amatiasq** [comment]
Closed due to lack of discussion :)
