### ISSUE TITLE
Use a config file for config sort-imports

### ISSUE THREAD

**Issue by hstarorg** [amatiasq/vsc-sort-imports#27]
Config in `package.json` is hard for use.

**Comment by amatiasq** [comment]
I agree, unfortunately it's not in our hand since we are forced to use [import-sort-config](https://github.com/renke/import-sort/tree/master/packages/import-sort-config) because we're using `import-sort`.

I'm sure they will accept a PR which improves the configuration mechanism. After that we'll be more than happy to update to the last version.

**Comment by hstarorg** [comment]
Thanks, I hope so.

**Comment by amatiasq** [comment]
Closed due to lack of activity.
