### ISSUE TITLE
Extra line is getting added on sorting import

### ISSUE THREAD

**Issue by afzal273** [amatiasq/vsc-sort-imports#48]
Not sure if it's an issue, but when I save file it's adding an extra line between imports. Is it expected behavior? If so how do I turn it off? I don't want lines between my imports.

**Comment by amatiasq** [comment]
That's the style. You can choose the style with [this setting](https://github.com/amatiasq/vsc-sort-imports#use-a-different-style-or-parser).

I use [`"style":  "module"`](https://github.com/renke/import-sort/tree/master/packages/import-sort-style-module) but if you don't want blank lines I recommend you [`"style":  "module-compact"`](https://github.com/amatiasq/import-sort-style-module-compact)  which only keeps blank lines for imports without identifiers, because in their case order matters.

Or even build a style to make your heart happy :), if you do you can open a PR and add it to the list.
