### ISSUE TITLE
Configuration has moved to package.json instead of IDE settings

### ISSUE THREAD

**Issue by alextreppass** [amatiasq/vsc-sort-imports#5]
Hi, first - nice job taking over maintenance.

If I'm reading the 4.0.0 update notes correctly, `sort-imports.sort-type` has moved to `package.json` configuration instead, to be closer to the underlying [renke/import-sort](https://github.com/renke/import-sort) library.

I work in a large codebase with lots of other developers that all use different IDEs - and can't inflict my specific IDE settings on our shared package.json.

Any chance we could fall back to supporting the old VSCode `sort-imports.sort-type` config if values aren't specified in package.json?

**Comment by amatiasq** [comment]
I agree 100% with you. I made this fork because I wanted to have that configuration per IDE but to support `package.json` config I have to rollback to `import-sort-config` which has two behaviours:

- Load default settings
- Overwrite with `package.json` settings if exists
- Return that

So from outside we have no way to know if the output of `import-sort-config` is from `package.json` or the default settings.

The point is that we want to place the IDE settings between the default settings and the `package.json` settings or provide our IDE settings as the default configuration. But that tool doesn't allow that.

I opened [renke/import-sort#42](https://github.com/renke/import-sort/pull/42) which would allow us to do exactly that but I haven't had any response yet.

Other solution would be to fork (basically copy-paste) `import-sort-config` but I'm trying to avoid that.

If you see any other solution I'm really interested in finding a solution for this.

**Comment by cliffkoh** [comment]
@amatiasq, renke/import-sort#42 has been resolved :)

**Comment by amatiasq** [comment]
Yeah, I've seen it. I'm moving so I can't work on it for the next... two weeks more or less. As always PRs are welcome.

**Comment by alextreppass** [comment]
Excellent, thanks both!
