### ISSUE TITLE
Conflict with simple-import-sort

### ISSUE THREAD

**Issue by ghengeveld** [amatiasq/vsc-sort-imports#67]
I'm using [eslint-plugin-simple-import-sort](https://github.com/lydell/eslint-plugin-simple-import-sort) instead of sort-imports. Because they sort [slightly differently](https://github.com/lydell/eslint-plugin-simple-import-sort#why-sort-on-from) they sometimes conflict. I could disable the VSC extension for the workspace but it'd be nicer if vsc-sort-imports didn't conflict like that, either by supporting the same sorting order (by path instead of name) or detect the presence of the simple-import-sort ESLint plugin when using the `eslint` style setting.

**Comment by amatiasq** [comment]
`vsc-sort-import` sorting algorithm supports different styles and plugins [I built this one myself](https://github.com/amatiasq/import-sort-style-module-compact/blob/master/src/index.ts) for example.

We can't hardcode a list of extensions that fulfill the same task as `vsc-sort-imports` because that would be unmaintainable.
